name: Build TWRP

on:
  workflow_dispatch:

# Required to allow GitHub Actions to create a Release tag and upload files
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          sudo docker image prune --all --force
          sudo apt clean

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git-core gnupg flex bison gperf build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 \
            lib32z1-dev \
            libgl1-mesa-dev \
            libxml2-utils xsltproc unzip \
            fontconfig python3 openjdk-11-jdk

      - name: Setup repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Init TWRP source
        run: |
          mkdir twrp
          cd twrp
          # Note: I kept your branch hook 'twrp-11' as specified in your script
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11

      - name: Sync source
        run: |
          cd twrp
          repo sync -c --no-clone-bundle --no-tags -j2 --force-sync

      - name: Clone device tree
        run: |
          cd twrp
          mkdir -p device/infinix
          git clone https://github.com/Hyylassx/Tree_infinix_X655C device/infinix/X655C

      - name: Debug tree
        run: |
          cd twrp/device/infinix/X655C
          pwd
          find . | head -50
      
      - name: Build recovery
        run: |
          cd twrp
          source build/envsetup.sh
          lunch omni_X655C-eng
          mka recoveryimage

      - name: Create Release Package
        run: |
          cd twrp/out/target/product/X655C/
          # Create a custom variable for a unique date tag
          echo "RELEASE_TAG=TWRP-X655C-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: TWRP Recovery for Infinix X655C
          body: |
            Automated TWRP Compilation Build.
            Target: Infinix Hot 9 (X655C)
            Platform: MediaTek MT6765
            Branch: Android 11 Minimal Manifest Base
          draft: false
          prerelease: false
          files: |
            twrp/out/target/product/X655C/recovery.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
