name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Recovery Action
        uses: XenonTheInertG/android-recovery-action@main
        env:
          MANIFEST: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11"
          DT_LINK: "https://github.com/Hyylassx/Tree_infinix_X655C"
          VENDOR: "infinix"
          CODENAME: "X655C"
          TARGET: "recoveryimage"
          FLAVOR: "eng"
          TZ: "Asia/Jakarta"

      - name: Upload Recovery
        uses: actions/upload-artifact@v4
        with:
          name: recovery
          path: |
            out/target/product/X655C/*.img
